"""upgrade Todo model

Revision ID: d765d57a8088
Revises: cbbce34a8af4
Create Date: 2025-04-15 10:37:23.899900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd765d57a8088'
down_revision: Union[str, None] = 'cbbce34a8af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.String(),
               type_=sa.Boolean(),
               postgresql_using='completed::boolean')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.Boolean(),
               type_=sa.String())
    # ### end Alembic commands ###
